#test
version: '3.3'
services:
  backend:
    container_name: image_service
    image: image_service
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING2}
      # - DB_CONNECTION_STRING=mongodb://192.168.3.165:27017/images
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  # frontend:
  #   container_name: angular_sample
  #   image: angular_sample:1.0.0
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   command: npm start
  #   ports:
  #     - 4210:4200
  #     - 9228:9229
  #   networks:
  #     - nesjs-network
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge
